version: "3.7"
services:
  cache:
    image: memcached
  db:
    image: mysql:8
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumen
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
  frontend:
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build:
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    links:
      - db
      - cache
